# Generated by Django 4.0.2 on 2022-03-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_list_item_list'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('text', 'list'), name='uniq list with text'),
        ),
    ]
