# Generated by Django 4.0.2 on 2022-03-11 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_item_uniq list with text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
    ]
